language: ruby
bundler_args: "--without production"
rvm:
- 2.2.2
before_script:
- psql -c 'create database comeals_test;' -U postgres
- bundle exec rake db:schema:load
addons:
  code_climate:
    repo_token: 802526f4a8297a7ded5bfaa85c0fab8d5726a6e6401376bdca55e53c84674202
